In [1]:
import pandas as pd
from sklearn.decomposition import PCA
from scipy import stats
import numpy as np
from sklearn.preprocessing import scale
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('Data/Normalized_Data_45.csv', index_col = 0)

In [3]:
df.head()

,BBLE,FULLVAL_LOTAREA_By_B,FULLVAL_BLDAREA_By_B,FULLVAL_BLDTOT_By_B,AVLAND_LOTAREA_By_B,AVLAND_BLDAREA_By_B,AVLAND_BLDTOT_By_B,AVTOT_LOTAREA_By_B,AVTOT_BLDAREA_By_B,AVTOT_BLDTOT_By_B,...,AVTOT_BLDTOT_By_ZIP3,FULLVAL_LOTAREA_By_ALL,FULLVAL_BLDAREA_By_ALL,FULLVAL_BLDTOT_By_ALL,AVLAND_LOTAREA_By_ALL,AVLAND_BLDAREA_By_ALL,AVLAND_BLDTOT_By_ALL,AVTOT_LOTAREA_By_ALL,AVTOT_BLDAREA_By_ALL,AVTOT_BLDTOT_By_ALL
0,1000010101,-0.060695,0.900334,0.875543,-0.020193,0.234715,0.171356,-0.046539,0.386116,0.403223,...,0.399005,-0.040315,0.815228,0.516371,-0.009311,0.455053,0.266218,-0.026968,0.921792,0.597876
1,1000010201,7.568010,2.510020,2.430665,2.257913,0.234211,0.170981,11.044536,1.057236,1.103096,...,1.093064,5.325068,2.277482,1.472711,9.277554,0.454095,0.265648,40.122670,2.490184,1.623048
2,1000020001,-0.019102,-0.035136,-0.028216,0.048062,0.002963,-0.001238,0.013932,-0.003906,-0.003508,...,-0.004348,-0.011062,-0.034561,-0.039406,0.268935,0.014352,0.003780,0.191938,0.010321,0.002097
3,1000020023,-0.051506,0.029037,0.078889,0.000277,0.035812,0.040688,-0.033180,0.022849,0.044694,...,0.043453,-0.033852,0.023734,0.026459,0.074137,0.076818,0.067530,0.021393,0.072847,0.072703
4,1000030001,0.057593,5.924273,17.300424,0.200544,3.424277,7.663595,0.125435,2.480728,7.795132,...,7.729515,0.042879,5.379022,10.617038,0.890542,6.520353,11.658580,0.595578,5.816850,11.425531

In [4]:
df.describe()

,FULLVAL_LOTAREA_By_B,FULLVAL_BLDAREA_By_B,FULLVAL_BLDTOT_By_B,AVLAND_LOTAREA_By_B,AVLAND_BLDAREA_By_B,AVLAND_BLDTOT_By_B,AVTOT_LOTAREA_By_B,AVTOT_BLDAREA_By_B,AVTOT_BLDTOT_By_B,FULLVAL_LOTAREA_By_TAXCLASS,...,AVTOT_BLDTOT_By_ZIP3,FULLVAL_LOTAREA_By_ALL,FULLVAL_BLDAREA_By_ALL,FULLVAL_BLDTOT_By_ALL,AVLAND_LOTAREA_By_ALL,AVLAND_BLDAREA_By_ALL,AVLAND_BLDTOT_By_ALL,AVTOT_LOTAREA_By_ALL,AVTOT_BLDAREA_By_ALL,AVTOT_BLDTOT_By_ALL
count,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,...,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06
mean,-2.781150e-17,-8.810514e-18,-2.600694e-18,5.042162e-19,-1.393229e-18,-1.758122e-18,2.091170e-17,2.985490e-18,5.373883e-19,7.287250e-17,...,-2.607328e-18,1.756795e-17,9.553569e-19,2.993452e-17,6.740574e-18,1.295371e-18,-1.127023e-18,5.864830e-18,1.099656e-17,7.304500e-18
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,-6.840049e-02,-6.434431e-02,-5.643475e-02,-2.635654e-02,-1.108156e-02,-1.169700e-02,-5.774148e-02,-1.608378e-02,-1.620737e-02,-1.621661e-01,...,-1.694218e-02,-4.573400e-02,-6.109445e-02,-5.675934e-02,-3.443703e-02,-1.235528e-02,-1.212405e-02,-6.751982e-02,-1.813836e-02,-1.650531e-02
25%,-5.513184e-02,-4.352205e-02,-4.115201e-02,-1.926665e-02,-9.494364e-03,-1.067789e-02,-4.580364e-02,-1.190858e-02,-1.262539e-02,-1.061171e-01,...,-1.333648e-02,-3.592515e-02,-4.193930e-02,-4.188206e-02,-2.730434e-02,-1.083544e-02,-1.117836e-02,-5.579881e-02,-1.395446e-02,-1.316833e-02
50%,-3.676316e-02,-1.091802e-02,-1.181433e-02,-1.027778e-02,-7.092950e-03,-8.168740e-03,-3.320353e-02,-9.272198e-03,-9.960520e-03,-5.556077e-02,...,-1.010252e-02,-2.558000e-02,-1.081940e-02,-9.568026e-03,-2.025534e-02,-8.265485e-03,-8.617151e-03,-4.846236e-02,-1.162656e-02,-1.048293e-02
75%,1.070227e-03,8.208763e-03,6.256513e-03,-6.820254e-04,-5.385987e-03,-6.490651e-03,-1.433494e-02,-6.595207e-03,-7.208774e-03,6.358275e-03,...,-7.231778e-03,-1.362716e-02,8.221904e-03,1.004345e-02,-1.198909e-02,-6.777144e-03,-7.166300e-03,-3.739287e-02,-9.422532e-03,-8.102623e-03
max,4.270492e+02,5.248266e+02,4.918919e+02,8.409995e+02,7.500455e+02,6.930676e+02,5.634308e+02,6.671628e+02,6.650325e+02,5.889111e+02,...,6.950223e+02,1.106749e+02,5.219301e+02,5.825879e+02,8.676148e+02,6.345051e+02,6.448654e+02,6.143945e+02,5.598618e+02,6.245636e+02

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1070994 entries, 0 to 1070993
Data columns (total 46 columns):
BBLE                           1070994 non-null object
FULLVAL_LOTAREA_By_B           1070994 non-null float64
FULLVAL_BLDAREA_By_B           1070994 non-null float64
FULLVAL_BLDTOT_By_B            1070994 non-null float64
AVLAND_LOTAREA_By_B            1070994 non-null float64
AVLAND_BLDAREA_By_B            1070994 non-null float64
AVLAND_BLDTOT_By_B             1070994 non-null float64
AVTOT_LOTAREA_By_B             1070994 non-null float64
AVTOT_BLDAREA_By_B             1070994 non-null float64
AVTOT_BLDTOT_By_B              1070994 non-null float64
FULLVAL_LOTAREA_By_TAXCLASS    1070994 non-null float64
FULLVAL_BLDAREA_By_TAXCLASS    1070994 non-null float64
FULLVAL_BLDTOT_By_TAXCLASS     1070994 non-null float64
AVLAND_LOTAREA_By_TAXCLASS     1070994 non-null float64
AVLAND_BLDAREA_By_TAXCLASS     1070994 non-null float64
AVLAND_BLDTOT_By_TAXCLASS      1070994 non-null float64
AVTOT_LOTAREA_By_TAXCLASS      1070994 non-null float64
AVTOT_BLDAREA_By_TAXCLASS      1070994 non-null float64
AVTOT_BLDTOT_By_TAXCLASS       1070994 non-null float64
FULLVAL_LOTAREA_By_ZIP5        1070994 non-null float64
FULLVAL_BLDAREA_By_ZIP5        1070994 non-null float64
FULLVAL_BLDTOT_By_ZIP5         1070994 non-null float64
AVLAND_LOTAREA_By_ZIP5         1070994 non-null float64
AVLAND_BLDAREA_By_ZIP5         1070994 non-null float64
AVLAND_BLDTOT_By_ZIP5          1070994 non-null float64
AVTOT_LOTAREA_By_ZIP5          1070994 non-null float64
AVTOT_BLDAREA_By_ZIP5          1070994 non-null float64
AVTOT_BLDTOT_By_ZIP5           1070994 non-null float64
FULLVAL_LOTAREA_By_ZIP3        1070994 non-null float64
FULLVAL_BLDAREA_By_ZIP3        1070994 non-null float64
FULLVAL_BLDTOT_By_ZIP3         1070994 non-null float64
AVLAND_LOTAREA_By_ZIP3         1070994 non-null float64
AVLAND_BLDAREA_By_ZIP3         1070994 non-null float64
AVLAND_BLDTOT_By_ZIP3          1070994 non-null float64
AVTOT_LOTAREA_By_ZIP3          1070994 non-null float64
AVTOT_BLDAREA_By_ZIP3          1070994 non-null float64
AVTOT_BLDTOT_By_ZIP3           1070994 non-null float64
FULLVAL_LOTAREA_By_ALL         1070994 non-null float64
FULLVAL_BLDAREA_By_ALL         1070994 non-null float64
FULLVAL_BLDTOT_By_ALL          1070994 non-null float64
AVLAND_LOTAREA_By_ALL          1070994 non-null float64
AVLAND_BLDAREA_By_ALL          1070994 non-null float64
AVLAND_BLDTOT_By_ALL           1070994 non-null float64
AVTOT_LOTAREA_By_ALL           1070994 non-null float64
AVTOT_BLDAREA_By_ALL           1070994 non-null float64
AVTOT_BLDTOT_By_ALL            1070994 non-null float64
dtypes: float64(45), object(1)
memory usage: 384.0+ MB

In [6]:
df_new = df.copy()

In [7]:
BBLE = df_new["BBLE"]

In [8]:
del df_new['BBLE']

In [9]:
df_new.shape

(1070994, 45)

In [10]:
mat = df_new.values

In [11]:
mat

array([[-6.06953291e-02,  9.00333603e-01,  8.75543260e-01, ...,
        -2.69675417e-02,  9.21792151e-01,  5.97875796e-01],
       [ 7.56801040e+00,  2.51001984e+00,  2.43066550e+00, ...,
         4.01226704e+01,  2.49018420e+00,  1.62304777e+00],
       [-1.91018022e-02, -3.51360381e-02, -2.82164959e-02, ...,
         1.91937880e-01,  1.03206433e-02,  2.09679687e-03],
       ...,
       [-5.14515489e-02,  9.75886907e-03,  4.35846421e-03, ...,
        -6.40227355e-02, -1.09117285e-02, -9.41979827e-03],
       [-2.91723081e-02,  3.14605381e-02,  2.21621956e-02, ...,
        -6.03456171e-02, -9.85705751e-03, -8.38572724e-03],
       [-7.98588319e-03,  1.35463690e-02,  7.46567370e-03, ...,
        -5.51898502e-02, -1.06248840e-02, -9.13855645e-03]])

In [12]:
pca=PCA(n_components=8)

In [13]:
newData=pca.fit_transform(mat)

In [14]:
newData.shape

(1070994, 8)

In [15]:
sum(pca.explained_variance_ratio_)

0.9711626441389866

In [16]:
df_pca = pd.DataFrame(newData)

In [17]:
df_pca['BBLE'] = BBLE

In [18]:
df_pca.shape

(1070994, 9)

In [19]:
df_pca.head()

,0,1,2,3,4,5,6,7,BBLE
0,2.619631,-1.050166,-0.701037,-0.639667,0.470781,0.853431,-0.963453,-0.006441,1000010101
1,21.555487,48.784965,13.494312,-6.142296,1.930685,18.123750,4.164618,1.037043,1000010201
2,-0.014236,0.217221,-0.017577,0.127023,-0.014757,-0.103249,-0.047280,0.053289,1000020001
3,0.171489,-0.192589,-0.120878,0.003208,-0.045045,-0.079808,-0.107460,-0.013175,1000020023
4,39.081468,-10.932879,-5.036673,-6.344450,-12.359707,10.349143,-10.582556,-11.443255,1000030001

In [20]:
df_test = df_pca.iloc[:,:-1]

In [21]:
df_norm_pca = pd.DataFrame(scale(df_test.values))

In [22]:
df_norm_pca.describe()

,0,1,2,3,4,5,6,7
count,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06
mean,-1.592262e-19,3.715277e-18,-1.220734e-18,2.972222e-18,-1.379960e-18,2.123015e-19,3.927578e-18,-1.167658e-18
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,-5.523464e-02,-3.532489e+02,-3.734528e+02,-1.374067e+02,-2.620035e+02,-2.984803e+02,-3.728210e+02,-2.385642e+02
25%,-2.741734e-02,-5.200524e-02,-2.551917e-02,4.165418e-03,-1.324567e-02,-1.170753e-01,-2.674133e-02,-3.930483e-02
50%,-1.325376e-02,-2.500217e-02,-1.119934e-02,2.050936e-02,6.587894e-03,-1.595876e-02,-6.769837e-04,-1.457085e-02
75%,-3.368170e-03,1.974859e-03,2.596637e-03,3.107457e-02,2.323445e-02,4.264441e-02,2.533818e-02,1.223135e-02
max,6.399767e+02,6.217572e+02,7.507433e+02,4.888844e+02,4.414824e+02,4.576030e+02,4.220742e+02,3.029731e+02

In [23]:
df_norm_pca['BBLE'] = BBLE

In [24]:
df_norm_pca.head()

,0,1,2,3,4,5,6,7,BBLE
0,0.535946,-0.340776,-0.378950,-0.409478,0.385434,0.752969,-0.966496,-0.007804,1000010101
1,4.410000,15.830565,7.294441,-3.931946,1.580675,15.990311,4.177770,1.256324,1000010201
2,-0.002913,0.070488,-0.009502,0.081313,-0.012082,-0.091095,-0.047430,0.064557,1000020001
3,0.035085,-0.062495,-0.065342,0.002053,-0.036879,-0.070413,-0.107799,-0.015961,1000020023
4,7.995610,-3.547684,-2.722607,-4.061353,-10.119040,9.130893,-10.615977,-13.862914,1000030001

In [25]:
df_norm_pca.to_csv('Data/PCA_Normalized.csv')